version: '3'
services:
  web:
    image: potzedd/owllook
    command: pipenv run gunicorn -c owllook/config/gunicorn.py --worker-class sanic.worker.GunicornWorker owllook.server:app
    ports:
     - "8001:8001"
    volumes:
     - .:/owllook
    networks:
     - caddy
    depends_on:
     - redis
     - mongo
     
  redis:
    image: redis:3.0
    ports:
     - "6379:6379"
    networks:
     - caddy
    command: redis-server
    
  mongo:
    image: mongo:3.6
    ports:
     - "27017:27017"
    networks:
     - caddy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  caddy:
    name: caddy
